package be.isach.ultracosmetics.v1_19_R1;

/**
 * This file automatically generated by obfuscatedfields_generator.py in tooling folder
 */
public class ObfuscatedFields {
    // corresponds to net.minecraft.world.entity.LivingEntity#jumping
    public static final String JUMPING = "%placeholder%";

    private ObfuscatedFields() {
    };
}
